### ISSUE TITLE
spec files are not valid JSON

### ISSUE THREAD

**Issue by tedstrauss** [psychoinformatics-de/datalad-hirni#122]
In the case of dicom import the spec file contains one JSON string for each dicom sequence. These are not assembled into a JSON array or other structure, but separated by a line break. As a result, the spec file is not valid JSON, which makes it less inter-operable. For instance, this tool could be used to make fine adjustments: https://jsoneditoronline.org/ 
Using a JSON array seems like the simplest solution to this.

**Comment by bpoldrack** [comment]
That's actually intentional and called a JSON stream. Two reasons:
a) we can process such a spec one line at a time without reading and evaluating the entire thing first
b) a `git diff` on such a spec is actually readable that way
