### ISSUE TITLE
Support notion of subject ID anonymization in studyspec

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#15]
ATM there is only one ID, the one extracted from the DICOMs. On conversion, we need to be able to map this into a new anonymized  subject ID.

It would be good to be able to assign such ID either in studyspec.json, or on `spec2bids`.

**Comment by bpoldrack** [comment]
Done in PR #21. Study spec now contains an `anon_subject` key in addition to the `subject` key, both of which can be passed into `dicom2spec` and `import-dcm` to overrule the default guessing.
