### ISSUE TITLE
how to contribute to documentation?

### ISSUE THREAD

**Issue by pvavra** [psychoinformatics-de/datalad-hirni#151]
@bpoldrack : After some conversation with Toemme and Linda, we agreed that we should help (at least) with improving the docs based on the things we have figured out so far. 
Hirni is just too useful to not use it ;-)

So, the question is: how?
Should we simply start creating pull-requests for the docs, or is there some better/preferred way of adding things? (didn't find any "to contribute do this" section in the docs/the github-readme..)

Are there any other people working on these docs (maybe or related things over at the datalad handbook?) with whom we should coordinate? Any development branches we should be aware of?

**Comment by bpoldrack** [comment]
@pvavra : Simple pull request is perfectly fine. There's no "hidden" process for the docs. Handbook is independent and should focus on datalad-core anyway.
