### ISSUE TITLE
Use of "datalad hirni-spec2bids --only-type" for physiological files 

### ISSUE THREAD

**Issue by lsempf** [psychoinformatics-de/datalad-hirni#165]
Hi! 

I would like to use the --only-type option to convert only physiological data to BIDS (and not behavioral data as well). I had therefore considered saving the physiological data with the type 'physio_file' and not 'events_file' in the studyspec.json 

The command would then be:
`datalad hirni-spec2bids --anonymize --only-type 'physio_file'`

I wonder if this is feasible or if it breaks something.

best regards :)

**Comment by bpoldrack** [comment]
Hi @lsempf,

sorry for missing your issues until now.

Yes, that's exactly the intention behind `type`.
