### ISSUE TITLE
Automatic creation of task-rest_events.tsv

### ISSUE THREAD

**Issue by lsempf** [psychoinformatics-de/datalad-hirni#166]
Hi, I ran into a problem during the bids conversion:

Hirni (presumably heudiconv) generates these task-rest_events.tsv files for resting state automatically as a default when converting DICOM to niftis. In our opinion hirni should delete these template files as they lead to bids warnings when checking the bids compatibility of the data: 

> 	Type:		Warning
	File:		        sub-014_ses-004_task-rest_events.tsv
	Location:	bids/sub-014/ses-004/func/sub-014_ses-004_task-rest_events.tsv
	Reason:		Tabular file contains custom columns not described in a data dictionary
	Evidence:	Columns: TODO -- fill in rows and add more tab-separated columns if desired not defined, please define in: /events.json, /task-rest_events.json,/sub-014/sub-014_events.json,/sub-014/sub-014_task-rest_events.json,/sub-014/ses-004/sub-014_ses-004_events.json,/sub-014/ses-004/sub-014_ses-004_task-rest_events.json,/sub-014/ses-004/func/sub-014_ses-004_events.json,/sub-014/ses-004/func/sub-014_ses-004_task-rest_events.json

**Comment by bpoldrack** [comment]
Thanks, @lsempf! I agree.

Technically, this needs to be addressed in https://github.com/psychoinformatics-de/hirni-toolbox. Therefore linked related issue above and will close here.
