### ISSUE TITLE
spec2bids requires manual `containers-add` with an undocumented container name

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#20]

**Comment by mih** [comment]
At least it is mentioned in #54 now.

**Comment by bpoldrack** [comment]
This now pretty much depends on what you want to use. `spec2bids` just calls procedures that may or may not be provided by github.com/psychoinformatics-de/hirni-toolbox (could be your own procedures, another toolbox, etc.). Either way it's not a `containers-add` anymore.

**Comment by mih** [comment]
> Either way it's not a containers-add anymore.

What did it become? http://imaging-docs.cbbs.eu/datamanagement/conversion/ still states the same info as last year.

**Comment by bpoldrack** [comment]
> What did it become?

`datalad install -s  https://github.com/psychoinformatics-de/hirni-toolbox somewhere/in/my/dataset`

**Comment by mih** [comment]
Please fix in the docs and close this issue.

**Comment by bpoldrack** [comment]
Docs are currently correctly saying, that this is done by `cfg_hirni`. It's also made clear that this needs to be run on study dataset. So - closing
