### ISSUE TITLE
Runtime info

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#28]
FYI @cni-md

For a SIEMENS Prisma type dataset with ~1h of BOLD scans it takes 1min to import it into a study dataset. This includes metadata aggregation from the DICOMs.

**Comment by cni-md** [comment]
Nice. I will check when the RAID reconstruction is done.

**Comment by mih** [comment]
Imported a full study with 7 subjects and 4x1h scan sessions now. Takes ~30min (linear scaling), and produced <600k in aggregated metadata from all scans combined, across 84 metadata object files (half of them uncompressed). The importer leaves a combined >80 commit that nicely document: import, metadata extraction, and studyspec generation for each acquisition.

**Comment by mih** [comment]
Conversion to BIDS took 2.5min per session (with 28 sessions).

- size of bids dataset: 66GB without all input dicoms
- down to 19GB (same as DICOM sourcedata) after uninstalling the sourcedata/ dataset with the dicoms
- also

```
% du -sh .git/objects
29M     .git/objects
% git gc
% du -sh .git/objects
470K    .git/objects
```
