### ISSUE TITLE
Support acq- scan property

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#41]
This is needed to get multi resolution acquisitions with a constant task supported properly.

**Comment by bpoldrack** [comment]
I'm not quite sure, what exactly you mean by "support". Are we talking about BIDS conversion or an adaption of the import layout?

**Comment by mih** [comment]
Can I add `bids_acq` to the studyspec and will get a `acq-...` filename component in a bids converted dataset? If not, this is what I mean ;-)

**Comment by mih** [comment]
Same actually goes for lots of other properties, and I think the deterministic follows an "I do only what people have thought of" approach, rather than "I can do everything the standard would allow". Following the BIDS idea, it should actually allow for anything current BIDS allows, and also more than that.

**Comment by bpoldrack** [comment]
Ok, got it.
