### ISSUE TITLE
Kill `spec2bids --target-dir`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#47]
I cannot see a clear use case that this would help with (other than the abstract "but if someone wants to output into an arbitrary directory"). OTOH it causes real problems with information leakage into run records, and their portability.

Unless we have a real use case that is worth this cost, we should kill it IMHO.

**Comment by bpoldrack** [comment]
Right. It's a left-over from when it was build to operate on the studydataset instead of the BIDS dataset.
