### ISSUE TITLE
Heuristic file referenced in non-reprodicible way in run record

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/datalad-hirni#56]
Example record, notice the full path to the heuristic file. This could be fixed by having a shim shipped by heudiconv that only imports the real heuristic shipped by hirni. 

```
{
  "chain": [],
  "cmd": "singularity exec --bind {pwd} .datalad/environments/conversion/image heudiconv -f /home/mih/hacking/hirni/datalad_hirni/support/hirni_heuristic.py -s XX -c dcm2niix -o .git/hirni-tmp-70f4s1j8 -b -a '{dspath}' -l '' --minmeta --files sourcedata/XX/dicoms",
  "dsid": "5b1081d6-84d7-11e8-b00a-a0369fb55db0",
  "exit": 0,
  "inputs": [
    "sourcedata/XX/dicoms",
    "sourcedata/XX/studyspec.json",
    ".datalad/environments/conversion/image"
  ],
  "outputs": [
    "."
  ],
  "pwd": "."
}
```

**Comment by mih** [comment]
Still an issue. Now somewhat wore as the path of the imported module is used, hence will be different between PY2 and PY3.

**Comment by bpoldrack** [comment]
Should be solved. Heuristic file and heudiconv image are now part of the toolbox. Referenced in the dataset's commit should be the called procedure from the toolbox.
