### ISSUE TITLE
Remove reference volumes

### ISSUE THREAD

**Issue by bpoldrack** [psychoinformatics-de/datalad-hirni#64]
While converting studyforrest phase1 it became clear that the current conversion via heudiconv includes the reference volume while the existing convertion via mcverter doesn't.
We probably should provide some routine to remove those automatically. We could even detect this by comparing first volumes across runs.
Could be done in a post conversion procedure or from within `spec2bids` via a switch. Since it's actually a post conversion processing step, I'd separate from `spec2bids`. Considering, that we also want some post conversion routine for defacing, we might even want to combine those to into some hirni standard preprocessing routine.

**Comment by mih** [comment]
There is really only one possibility without having to impose custom logic on heudiconv: We have to post-process the images after conversion.

**Comment by bpoldrack** [comment]
As far as hirni is concerned, this is solved. Needs to be a bit nicer for the toolbox, though.
