### ISSUE TITLE
Remove setup_bids_dataset procedure

### ISSUE THREAD

**Issue by bpoldrack** [psychoinformatics-de/datalad-hirni#89]
This procedure should likely live in datalad-neuroimaging instead of datalad-hirni.

**Comment by mih** [comment]
-neuroimaging has an (improved) `cfg_bids` procedure now. This one in here should be removed ASAP.

**Comment by mih** [comment]
It is gone already. Only mentioned by `docs/source/demos/conversion.rst` as a last remaining trace.
