### ISSUE TITLE
how to install most recent version from github + version number

### ISSUE THREAD

**Issue by pvavra** [psychoinformatics-de/datalad-hirni#92]
When landing the repo and looking for install instructions, there is only the reference to the `pip install` path. I suggest to add also clear instructions on how to install the extension directly from github. 

Related to that, when running `datalad wtf`, currently there is no version number listed. I propose to adding version numbers, so that users can quickly and easily assert which version is being used by datalad.

**Comment by pvavra** [comment]
quick general follow-up question: 
do you want me to create pull requests for such simple changes (although not sure where `datalad wtf` looks for version info..)?

**Comment by bpoldrack** [comment]
> quick general follow-up question:
do you want me to create pull requests for such simple changes

It's absolutely fine to just report such things. But it's even better if you make a pull request, of course!

**Comment by mih** [comment]
> Related to that, when running datalad wtf, currently there is no version number listed. I propose to adding version numbers, so that users can quickly and easily assert which version is being used by datalad.

That is not an issue of `wtf`. It is due to `hirni.__init__.py` not having a `__version__` symbol. If that is added, `wtf`will report a version, as it does for other extensions.
